[window]
padding = { x = 10, y = 10 }
decorations = "None"
opacity = 1.0

[font]
size = 15

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[selection]
save_to_clipboard = true

[terminal]
shell = "/bin/zsh"

[mouse]
hide_when_typing = true

